---
originRequest:
  originServerName: external.tslamars.com

ingress:
  - hostname: tslamars.com
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.tslamars.com"
    service: *svc
  - service: http_status:404
